/* Generated By:JavaCC: Do not edit this line. HelloConstants.java */
package egtry.hello;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HelloConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHANUMERIC = 16;
  /** RegularExpression Id. */
  int QOUTE = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"ADD\"",
    "\"WITH\"",
    "\"IMAGE\"",
    "\"SOURCE\"",
    "\"HEADING\"",
    "\"PARAGRAPH\"",
    "\"LINK\"",
    "\"AND\"",
    "\"TEXT\"",
    "\"COLOR\"",
    "\"FONT\"",
    "<ALPHANUMERIC>",
    "\"\\\"\"",
    "\"WITH LINK\"",
  };

}
